apiVersion: draveness.me/v1alpha1
kind: Proxier
metadata:
  name: example-proxier
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678
  selector:
    app: test
  backends:
    - name: v1
      weight: 1
      selector:
        version: v1
    - name: v2
      weight: 9
      selector:
        version: v2
