apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: proxiers.maegus.com
spec:
  group: maegus.com
  names:
    kind: Proxier
    listKind: ProxierList
    plural: proxiers
    singular: proxier
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backends:
              items:
                properties:
                  name:
                    minLength: 1
                    type: string
                  selector:
                    additionalProperties:
                      type: string
                    type: object
                  weight:
                    format: int32
                    minimum: 1
                    type: integer
                required:
                - name
                - weight
                type: object
              minItems: 1
              type: array
            ports:
              items:
                properties:
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                  targetPort:
                    oneOf:
                    - type: string
                    - type: integer
                required:
                - port
                type: object
              type: array
            selector:
              additionalProperties:
                type: string
              type: object
          required:
          - backends
          - ports
          type: object
        status:
          properties:
            currentBackends:
              format: int32
              type: integer
            obsoleteBackends:
              format: int32
              type: integer
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
