apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: proxiers.maegus.com
spec:
  group: maegus.com
  names:
    kind: Proxier
    listKind: ProxierList
    plural: proxiers
    singular: proxier
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
