kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxier
subjects:
- kind: ServiceAccount
  name: proxier
roleRef:
  kind: ClusterRole
  name: proxier
  apiGroup: rbac.authorization.k8s.io
