apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxier-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: proxier-operator
  template:
    metadata:
      labels:
        name: proxier-operator
    spec:
      serviceAccountName: proxier
      containers:
        - name: proxier
          image: draveness/proxier:v0.2.0
          command:
          - proxier
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "proxier-operator"
