apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxier-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: proxier
  template:
    metadata:
      labels:
        name: proxier
    spec:
      serviceAccountName: proxier
      containers:
        - name: proxier
          image: draveness/proxier:v0.0.4
          command:
          - proxier
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "proxier"
