---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: proxier
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - proxier
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - maegus.com
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxier
subjects:
- kind: ServiceAccount
  name: proxier
  namespace: default
roleRef:
  kind: ClusterRole
  name: proxier
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: proxiers.maegus.com
spec:
  group: maegus.com
  names:
    kind: Proxier
    listKind: ProxierList
    plural: proxiers
    singular: proxier
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backends:
              items:
                properties:
                  name:
                    minLength: 1
                    type: string
                  selector:
                    additionalProperties:
                      type: string
                    type: object
                  weight:
                    format: int32
                    minimum: 1
                    type: integer
                required:
                - name
                - weight
                type: object
              minItems: 1
              type: array
            ports:
              items:
                properties:
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                  targetPort:
                    oneOf:
                    - type: string
                    - type: integer
                required:
                - port
                type: object
              type: array
            selector:
              additionalProperties:
                type: string
              type: object
          required:
          - backends
          - ports
          type: object
        status:
          properties:
            phase:
              type: string
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxier-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: proxier-operator
  template:
    metadata:
      labels:
        name: proxier-operator
    spec:
      serviceAccountName: proxier
      containers:
        - name: proxier
          image: draveness/proxier:v0.1.2
          command:
          - proxier
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "proxier-operator"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxier
