kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxier
subjects:
- kind: ServiceAccount
  name: proxier
roleRef:
  kind: Role
  name: proxier
  apiGroup: rbac.authorization.k8s.io
